// <auto-generated />
using E_Commerce_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerce_App.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Commerce_App.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Laptops"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Accessories"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Screens"
                        });
                });

            modelBuilder.Entity("E_Commerce_App.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Powerful laptop for professionals",
                            Name = "MacBook Pro",
                            Price = 1499m,
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Sleek and high-performance laptop",
                            Name = "Dell XPS 13",
                            Price = 1299m,
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "Gaming laptop",
                            Name = "Lenovo LEGION 5",
                            Price = 999m,
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "Stylish and durable laptop carrying bag",
                            Name = "Laptop Bag",
                            Price = 49m,
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Description = "Ergonomic wireless mouse",
                            Name = "Wireless Mouse",
                            Price = 19m,
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Description = "Adjustable laptop stand for better ergonomics",
                            Name = "Laptop Stand",
                            Price = 29m,
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            Description = "Full HD monitor for crisp visuals",
                            Name = "24-Inch Monitor",
                            Price = 199m,
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 3,
                            Description = "High-resolution 4K monitor with vibrant colors",
                            Name = "27-Inch 4K Monitor",
                            Price = 399m,
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 3,
                            Description = "Sturdy stand to hold two monitors for multitasking",
                            Name = "Dual Monitor Stand",
                            Price = 89m,
                            StockQuantity = 10
                        });
                });

            modelBuilder.Entity("E_Commerce_App.Models.Product", b =>
                {
                    b.HasOne("E_Commerce_App.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("E_Commerce_App.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
